config/urls.py
from django.contrib import admin
from django.urls import include, path
from web_project.views import SystemView

urlpatterns = [
    path("admin/", admin.site.urls),

    # Api
    path("api/v1/", include("apps.api.urls")),

    # Front-end urls
    path("", include("apps.common.urls")),


]

handler404 = SystemView.as_view(template_name="pages_misc_error.html", status=404)
handler400 = SystemView.as_view(template_name="pages_misc_error.html", status=400)
handler500 = SystemView.as_view(template_name="pages_misc_error.html", status=500)

apps/recipe_app/models.py
from django.db import models
from django.db.models import Avg, Count
from apps.user_app.models import User
from apps.common.models import BaseModel

class Ingredient(models.Model):
    """
    Model to store information about ingredients.
    """
    name = models.CharField(max_length=255)

class RecipeIngredientQuantity(models.Model):
    """
    Model to store quantities of ingredients for recipes.
    """
    ingredient = models.ForeignKey(Ingredient, related_name='ingredient_base', on_delete=models.CASCADE)
    recipe = models.ForeignKey("Recipe", related_name='ingredients', on_delete=models.CASCADE)
    quantity_original = models.CharField(max_length=255)
    quantity_normalized = models.FloatField(null=True)
    units_normalized = models.CharField(default='G', max_length=255)
    extra_quantity = models.FloatField(null=True)
    extra_units = models.CharField(max_length=255, null=True)

class NutritionInformation(models.Model):
    """
    Model to store nutrition information for recipes.
    """
    energia = models.FloatField(null=True)
    energia_perc = models.FloatField(null=True)
    gordura = models.FloatField(null=True)
    gordura_perc = models.FloatField(null=True)
    gordura_saturada = models.FloatField(null=True)
    gordura_saturada_perc = models.FloatField(null=True)
    hidratos_carbonos = models.FloatField(null=True)
    hidratos_carbonos_perc = models.FloatField(null=True)
    hidratos_carbonos_acucares = models.FloatField(null=True)
    hidratos_carbonos_acucares_perc = models.FloatField(null=True)
    fibra = models.FloatField(null=True)
    fibra_perc = models.FloatField(null=True)
    proteina = models.FloatField(null=True)
    proteina_perc = models.FloatField(null=True)


class Recipe(BaseModel):
    title = models.CharField(max_length=255, null=False)
    description = models.TextField( null=False)
    img_source = models.CharField(max_length=255, null=True)
    verified = models.BooleanField(default=False)
    difficulty = models.CharField(max_length=255, null=True)
    portion = models.CharField(max_length=255, null=True)
    time = models.CharField(max_length=255, null=True)
    views = models.IntegerField(default=0, null=False)
    created_by = models.ForeignKey(User, related_name='created_recipes', on_delete=models.CASCADE)
    nutrition_information = models.OneToOneField(NutritionInformation, related_name='recipe', null=True, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)
    source_rating = models.FloatField(null=True)
    source_link = models.CharField(max_length=255, null=True,unique=True)
    
    users_liked = models.ManyToManyField(User, related_name='liked_recipes', blank=True)
    users_saved = models.ManyToManyField(User, related_name='saved_recipes', blank=True)

    def get_average_rating(self):
        return self.ratings.aggregate(avg_rating=Avg('rating'))['avg_rating'] or 0.0

    def save_audited(self, *args, **kwargs):
            
            # Recipe Audit Log changing user
            
            if self.pk is not None:
                user = kwargs.pop('user', None)  # Remove 'user' from kwargs if present, or default to None
        
                if user is None:
                    # Assuming you have access to request object in the view or other context
                    if hasattr(self, '_request') and self._request.user.is_authenticated:
                        user = self._request.user
                    else:
                        raise ValueError("User must be provided or authenticated to save this model.")
                
                # Retrieve the current instance from the database
                old_instance = self.__class__.objects.get(pk=self.pk)
                

                
                for field in self._meta.fields:
                    if getattr(self, field.attname) != getattr(old_instance, field.attname):
                        RecipeAuditLog.objects.create(
                            recipe=self, field=field,
                            old_value=getattr(old_instance, field.attname),
                            new_value=getattr(self, field.attname),
                            user=kwargs['user']
                            ) 

                


            super(Recipe, self).save(*args, **kwargs)

            

    class Meta:
        ordering = ['-views']  # Order recipes by views in descending order


class Preparation(BaseModel):
    """
    Model to store tags for recipes.
    """
    step = models.CharField(max_length=2)
    description = models.TextField()
    recipe = models.ForeignKey(Recipe,on_delete=models.CASCADE, related_name='preparation')

class Tag(BaseModel):
    """
    Model to store tags for recipes.
    """
    title = models.CharField(max_length=255)
    recipes = models.ManyToManyField(Recipe, related_name='tags')


class RecipeRating(BaseModel):
    """
    Model to store ratings for recipes.
    """
    recipe = models.ForeignKey(Recipe, related_name='ratings', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='rated_recipes', on_delete=models.CASCADE)
    rating = models.IntegerField(null=True)


# to be removed
class RecipeBackground(BaseModel):
    """
    Model to store background information for recipes.
    """
    user = models.ForeignKey(User, related_name='recipes', on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, related_name='backgrounds', on_delete=models.CASCADE)
    type = models.CharField(max_length=255)



class Comment(BaseModel):
    """
    Model to store comments on recipes.
    """
    text = models.CharField(max_length=255)
    recipe = models.ForeignKey(Recipe, related_name='comments', on_delete=models.CASCADE, null=True)
    parent_comment = models.ForeignKey('self', related_name='comments', on_delete=models.CASCADE, null=True)
    likes = models.ManyToManyField(User, related_name='comment_likes')
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)

class RecipeReport(BaseModel):
    """
    Model to store reports on recipes.
    """
    title = models.CharField(max_length=255)
    message = models.CharField(max_length=255)
    recipe = models.ForeignKey(Recipe, related_name='reports', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='my_recipe_reports', on_delete=models.CASCADE)
    assigne = models.ForeignKey(User, related_name='recipe_reports', on_delete=models.CASCADE)
    

    class Type(models.TextChoices):
        NutritionInformation = 'NutritionInformation', 'Nutrition Information'
        Ingredient = 'Ingredient', 'Ingredient'
        Preparation = 'Preparation', 'Preparation'
        Detail = 'Detail', 'Detail'
        Other = 'Other', 'Other'

    type = models.CharField(
        max_length=20,
        choices=Type.choices,
        default=Type.Other,
        null=True
    )

    class Satus(models.TextChoices):
        RESOLVED = 'RESOLVED', 'Resolved'
        IN_PROGRESS = 'SEEN', 'Seen'
        ON_HOLD = 'ON_HOLD', 'On Hold'
        PENDING = 'PENDING', 'Pending'

    status = models.CharField(
        max_length=10,
        choices=Satus.choices,
        default=Satus.PENDING,
        null=True
    )
    
class RecipeAuditLog(models.Model):
    model_name = models.CharField(max_length=100)
    field_name = models.CharField(max_length=100)
    old_value = models.TextField(null=True, blank=True)
    new_value = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return f'{self.model_name} - {self.field_name} changed by {self.user}'

apps/recipe_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET, require_POST
from django.views import View
from django.urls import reverse
from django.core.paginator import Paginator
from django.views.generic import TemplateView

from web_project import TemplateLayout

from apps.etl_app.forms import TaskForm
from apps.etl_app.filters import TaskFilter
from apps.etl_app.models import Task
from apps.recipe_app.models import Recipe,RecipeReport
from apps.recipe_app.filters import RecipeFilter
from apps.recipe_app.forms import RecipeReportForm
from apps.common.constants import WEBSOCKET_HOST   

from firebase_admin import  storage

from os import path



from datetime import  timedelta


###
#
#   Views
#
##



###
#   General
##


@method_decorator(login_required, name='dispatch')
class RecipeTableView(TemplateView):
    template_name = 'recipe_app/recipe/table.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        
        records = Recipe.objects.all().order_by('-id')
        filter = RecipeFilter(self.request.GET, queryset=records)
        filtered_records = filter.qs
        
        #

        page_size = int(self.request.GET.get('page_size',self.page_size))
            
        paginator = Paginator(filtered_records, page_size)  # Show 10 tasks per page
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['filter'] = filter
        context['page_obj'] = page_obj
        
        return context

@method_decorator(login_required, name='dispatch')
class RecipeDetailView(TemplateView):
    template_name = 'recipe_app/recipe/recipe_detail.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        context['record'] = Recipe.objects.get(id=kwargs['id'])

        # Image

        # Reference to the image file in Firebase Storage
        bucket = storage.bucket()
        blob = bucket.blob(context['record'].img_source)
        
        # Get the download URL
        context['image_url'] = blob.generate_signed_url(timedelta(minutes=15))
        print(context['record'].nutrition_information)

        ## Reports

        records = context['record'].reports.all().order_by('-created_at')
        filter = RecipeFilter(self.request.GET, queryset=records)
        filtered_records = filter.qs
        
        ## Pagination

        page_size = int(self.request.GET.get('page_size',self.page_size))
            
        paginator = Paginator(filtered_records, page_size)  # Show 10 tasks per page
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['filter'] = filter
        context['page_obj'] = page_obj
        
        return context

@login_required
@require_GET
def recipe_edit(request, id):

    
    return redirect(request.path)

@login_required
@require_GET
def recipe_delete(request, id):
    instance = get_object_or_404(Task, id=id)
    
    instance.delete()
    
    return redirect('recipes')



###
#   ETL Tasks
##


@method_decorator(login_required, name='dispatch')
class RecipeTaskTableView(TemplateView):
    template_name = 'recipe_app/etl_recipe/table.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        
        records = Task.objects.all().order_by('-id')
        filter = TaskFilter(self.request.GET, queryset=records)
        filtered_records = filter.qs
        
        #

        page_size = int(self.request.GET.get('page_size',self.page_size))
            
        paginator = Paginator(filtered_records, page_size)  # Show 10 tasks per page
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['filter'] = filter
        context['page_obj'] = page_obj
        
        return context
    
@method_decorator(login_required, name='dispatch')
class RecipeTaskDetailView(TemplateView):
    template_name = 'recipe_app/etl_recipe/task_detail.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        context['task'] = Task.objects.get(id=kwargs['id'])
        
        log_path = context['task'].log_path

        if log_path and path.isfile(log_path):
            with open(log_path, 'r') as log_file:
                context['log'] = log_file.read()  # Read the entire content of the log file

        
        context['WEBSOCKET_HOST'] =  WEBSOCKET_HOST
        
        return context
    
    
@method_decorator(login_required, name='dispatch')
class RecipeTaskCreateView(TemplateView):
    template_name = 'recipe_app/etl_recipe/task_create.html'

    
    
    def get_context_data(self, **kwargs):
        # A function to init the global layout. It is defined in web_project/__init__.py file
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        context['form'] = TaskForm()
        
        return context

    def post(self, request, *args, **kwargs):
        
        form = TaskForm(request.POST)

        if form.is_valid():
            instance = form.save()
            return redirect(reverse('recipe_task_detail', args=[instance.id]))
        
        # Use get_context_data to include layout_path and other context variables
        context = self.get_context_data(**kwargs)
        context['form'] = form

        return render(request, self.template_name, context)
 
#@login_required
@require_GET
def recipe_task_restart(request, id):
    instance = get_object_or_404(Task, id=id)
    
    instance.restart()
    
    return redirect(reverse('recipe_task_detail', args=[instance.id])) 


@require_GET
def recipe_task_pause(request, id):
    instance = get_object_or_404(Task, id=id)
    
    instance.pause()
    
    return redirect(reverse('recipe_task_detail', args=[instance.id])) 

@require_GET
def recipe_task_resume(request, id):
    instance = get_object_or_404(Task, id=id)
    
    instance.resume()
    
    return redirect(reverse('recipe_task_detail', args=[instance.id])) 

@require_GET
def recipe_task_cancel(request, id):
    instance = get_object_or_404(Task, id=id)
    
    instance.cancel()
    
    return redirect(reverse('recipe_task_detail', args=[instance.id])) 

@login_required
@require_GET
def recipe_task_delete(request, id):
    instance = get_object_or_404(Task, id=id)
    
    instance.delete()
    
    return redirect('recipe_tasks')


###
#   Recipe Reports
##



@method_decorator(login_required, name='dispatch')
class RecipeReportTableView(TemplateView):
    template_name = 'recipe_app/report/table.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        
        records = RecipeReport.objects.all().order_by('-id')
        filter = TaskFilter(self.request.GET, queryset=records)
        filtered_records = filter.qs
        
        #

        page_size = int(self.request.GET.get('page_size',self.page_size))
            
        paginator = Paginator(filtered_records, page_size)  # Show 10 tasks per page
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        
        context['filter'] = filter
        context['page_obj'] = page_obj
        
        return context

@method_decorator(login_required, name='dispatch')
class RecipeReportCreateView(TemplateView):
    template_name = 'recipe_app/report/report_create.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        context['record'] = Recipe.objects.get(id=kwargs['id'])
        context['form'] = RecipeReportForm()
        
        return context
    
    
    def post(self, request, *args, **kwargs):

        form_data = request.POST.copy()
        form_data['recipe'] = kwargs.get('id') 
        form_data['user'] = request.user.id 
        print(form_data['user']  )
        print(form_data)
        form = RecipeReportForm(form_data) 

        if form.is_valid():
            instance = form.save()
            return redirect(reverse('recipe_report_detail', args=[instance.id]))

        
        # Use get_context_data to include layout_path and other context variables
        context = self.get_context_data(**kwargs)
        context['form'] = form

        return render(request, self.template_name, context)
    

@method_decorator(login_required, name='dispatch')
class RecipeReportDetailView(TemplateView):
    template_name = 'recipe_app/report/report_detail.html'
    page_size = 10

    def get_context_data(self, **kwargs):
        
        context = TemplateLayout.init(self, super().get_context_data(**kwargs))
        context['task'] = RecipeReport.objects.get(id=kwargs['id'])
        
        
        return context

templates/recipe_app/etl_recipe/table.html
{% extends layout_path %}

{% load static %}
{% load i18n %}

{% block title %}Recipe - Tasks{% endblock %}

{% block content %}
<h4 class="py-3 mb-4">
  <span class="text-muted fw-light">Recipe /</span> Tasks
</h4>


<!-- Basic Bootstrap Table -->
<div class="card">
  
  <div class="container-fluid d-flex align-items-center">
    <h5 class="card-header flex-grow-1">Recipe's ETL Tasks Table</h5>
    
    <a href="{% url 'recipe_task_create' %}" class="btn btn-primary">
      Create ETL Task
    </a>
  </div>
  
  <!-- Filter Form -->
  <form method="get" class="card py-3 mb-4">
    <div class="container-fluid d-flex align-items-center">
      
      <div class="col-md-2 pe-md-1">
        <label class="form-label">Type: </label>
        {{ filter.form.type}}
      </div>
      <div class="col-md-2 pe-md-1">
        <label class="form-label">Status: </label>
        {{ filter.form.status }}
      </div>
      <div class="col-md-2 pe-md-1">
        <label class="form-label">Started At: </label>
        {{ filter.form.started_at }}
      </div>
      <div class="col-md-2 pe-md-1">
        <label class="form-label">Finished At: </label>
        {{ filter.form.finished_at }}
      </div>
      <div class="col-md-4 text-end">
        <button type="submit" class="btn btn-primary">Filter</button>
      </div>
    </div>
    
  </form>
  
  <!-- Table -->
  <div class="table-responsive text-nowrap">
    <table class="table">
      <thead>
        <tr>
          <th>Task</th>
          <th>Users</th>
          <th>Type</th>
          <th>Status</th>
          <th>Started At</th>
          <th>Finished At</th>
          <th>Max Records</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for task in page_obj %}
        <tr >
          <td>{{ task.id }}</td>
          <td>{{ task.company.name }}</td>
          <td>{{ task.get_type_display }}</td>
          <td><span class="badge 
            {% if task.status == 'STARTING' %}
                bg-label-primary
            {% elif task.status == 'RUNNING' %}
                bg-label-info
            {% elif task.status == 'CANCELED' %}
                bg-label-warning
            {% elif task.status == 'FAILED' %}
                bg-label-danger
            {% elif task.status == 'FINISHED' %}
                bg-label-success
            {% else %}
                bg-label-secondary
            {% endif %}
            me-1">{{ task.get_status_display }}</span></td>
          <td>{{ task.started_at }}</td>
          <td>{{ task.finished_at }}</td>
          <td>{{ task.max_records }}</td>
          <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="bx bx-dots-vertical-rounded"></i></button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'recipe_task_detail' task.id %}"><i class="bx bx-detail me-1"></i> Details</a>
                <a class="dropdown-item" href="{% url 'recipe_task_delete' task.id %}"><i class="bx bx-trash me-1"></i> Delete</a>
              </div>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  
  {% include "default/pagination.html" %}
</div>
</div>
{% endblock %}

templates/recipe_app/etl_recipe/task_create.html
{% extends layout_path %}

{% load static %}
{% load i18n %}

{% block title %}Tables - Basic Tables{% endblock %}

{% block content %}

<h4 class="py-3 mb-4">
  <span class="text-muted fw-light">Recipe / Tasks / </span> Create ETL Task
</h4>

<div class="row justify-content-center">
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <form method="post">
          {% csrf_token %}

          <!-- Company field -->
          {{ form.company.label_tag }}
          <div class="col-md-12 mt-2 mb-3">
            {{ form.company }}
            {% if form.company.errors %}
              <div class="invalid-feedback d-block">
                {% for error in form.company.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}
          </div>

          <!-- Type field -->
          {{ form.type.label_tag }}
          <div class="col-md-12 mt-2 mb-3">
            {{ form.type }}
            {% if form.type.errors %}
              <div class="invalid-feedback d-block">
                {% for error in form.type.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}
          </div>

          <!-- Tasks Transformation field -->
          <div id="parent-tasks-transform" style="display: none;">
            {{ form.parent_tasks_transform.label_tag }}
            <div class="col-md-12 mt-2 mb-3">
              {{ form.parent_tasks_transform }}
              {% if form.parent_tasks_transform.errors %}
                <div class="invalid-feedback d-block">
                  {% for error in form.parent_tasks_transform.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          </div>

          <!-- Tasks Extraction field -->
          <div id="parent-tasks-extract" style="display: none;">
            {{ form.parent_tasks_extract.label_tag }}
            <div class="col-md-12 mt-2 mb-3">
              {{ form.parent_tasks_extract }}
              {% if form.parent_tasks_extract.errors %}
                <div class="invalid-feedback d-block">
                  {% for error in form.parent_tasks_extract.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          </div>

          <!-- Max records field -->
          {{ form.max_records.label_tag }}
          <div class="col-md-12 mt-2 mb-3">
            {{ form.max_records }}
            {% if form.max_records.errors %}
              <div class="invalid-feedback d-block">
                {% for error in form.max_records.errors %}
                  {{ error }}
                {% endfor %}
              </div>
            {% endif %}
          </div>

          <button type="submit" class="btn btn-primary">Submit</button>

        </form>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('#id_type').change(function() {
      console.log($(this).val());
      if ($(this).val() === 'LOAD') {
        $('#parent-tasks-extract').hide()
        $('#parent-tasks-transform').show();
      } else if ($(this).val() === 'TRANSFORM') {
        $('#parent-tasks-transform').hide()
        $('#parent-tasks-extract').show();
      } else{
        $('#parent-tasks-extract').hide()
        $('#parent-tasks-transform').hide()

      }
    });
    
    // Trigger change event on page load if type is pre-selected
    $('#id_type').change();
  });
</script>
{% endblock %}

templates/recipe_app/etl_recipe/task_detail.html
{% extends layout_path %}

{% load static %}
{% load i18n %}

{% block title %}Perfect Scrollbar - Extended UI{% endblock %}

{% block vendor_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
{% endblock vendor_css %}

{% block vendor_js %}
{{ block.super }}
<script src="{% static 'vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
{% endblock vendor_js %}

{% block page_js %}
{{ block.super }}
<script src="{% static 'js/extended-ui-perfect-scrollbar.js' %}"></script>
{% endblock page_js %}

{% block content %}
<h4 class="py-3 mb-4">
    <span class="text-muted fw-light">Tables / Recipe's ETL Tasks / </span> Task {{task.id}} details
</h4>

<div class="row">
    <!-- Vertical Scrollbar -->
    <div class="col-md-12 col-sm-12">
        <div class="card overflow-hidden mb-4" style="height: auto;">
            <div class="container-fluid d-flex align-items-center justify-content-between">
                <h5 class="card-header">Task Details</h5>
                <div>
                    <a href="{% url 'recipe_task_pause' task.id%}" class="btn btn-primary py-1">
                        Pause
                    </a>
                    <a href="{% url 'recipe_task_resume' task.id%}" class="btn btn-primary py-1">
                        Resume
                    </a>
                    <a href="{% url 'recipe_task_cancel' task.id%}" class="btn btn-primary py-1">
                        Cancel
                    </a>
                    <a href="{% url 'recipe_task_restart' task.id%}" class="btn btn-primary py-1">
                        Restart
                    </a>
                    <a href="{% url 'recipe_task_delete' task.id %}" class="btn btn-danger py-1">
                        Delete
                    </a>
                </div>
            </div>
            <div class="card-body task-details">
                <div class="row">
                    <div class="col-md-3">
                        <h6>User:</h6>
                        <p class="badge bg-label-primary me-1">{{ task.company }}</p>
                    </div>
                    <div class="col-md-3">
                        <h6>Type:</h6>
                        <p class="badge bg-label-primary me-1">{{ task.type }}</p>
                    </div>
                    <div class="col-md-4">
                        <h6>Status:</h6>
                        <span class="
                        badge 
                        {% if task.status == 'STARTING' %}
                            bg-label-primary
                        {% elif task.status == 'RUNNING' %}
                            bg-label-info
                        {% elif task.status == 'CANCELED' %}
                            bg-label-warning
                        {% elif task.status == 'FAILED' %}
                            bg-label-danger
                        {% elif task.status == 'FINISHED' %}
                            bg-label-success
                        {% else %}
                            bg-label-secondary
                        {% endif %}
                        me-1">{{ task.get_status_display }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <h6>Max Records:</h6>
                        <p class="badge bg-label-primary me-1">{{ task.max_records }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <h6>Started At:</h6>
                        <p class="badge bg-label-primary  me-1">{{ task.started_at }}</p>
                    </div>
                    <div class="col-md-3">
                        <h6>Finished At:</h6>
                        <p class="badge bg-label-primary me-1">{{ task.finished_at }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ Vertical Scrollbar -->
    
    <!-- Vertical & Horizontal Scrollbars -->
    <div class="col-12">
        <div class="card overflow-hidden" style="height: 500px;">
            <div class="container-fluid d-flex align-items-center">
                <h5 class="card-header">Log</h5>
            </div>
            <div class="card-body" id="both-scrollbars-example">
                <div id="log-container" style="white-space: pre-wrap; margin-top: 10px;">{{ log|safe }}</div>
            </div>
        </div>
    </div>
    <!--/ Vertical & Horizontal Scrollbars -->
</div>

<script>
    const logContainer = document.getElementById('log-container');
    const logPath = "{{ task.log_path }}";
    const socket = new WebSocket('ws://{{ WEBSOCKET_HOST }}/ws/logs/?file=' + encodeURIComponent(logPath));
    
    socket.onmessage = function(event) {
        const newLog = document.createTextNode(event.data);
        logContainer.appendChild(newLog);

        logContainer.scrollTop = logContainer.scrollHeight;
    };
</script>
{% endblock %}